apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  type: LoadBalancer  # Change to NodePort if you're not using a cloud provider that supports LoadBalancers
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-boot-app
